name: "Conflict-Butt"
description: "Check for conflicts against other open PRs"
inputs:
  github-token:
    description: "GitHub token"
    required: true
  main-branch:
    description: "Name of main branch (defaults to 'main')"
    required: false
  quiet:
    description: "Only request reviews without commenting (defaults to 'false')"
    required: false
runs:
  using: node12
  main: index.js
